[project]
  name = "personal-scripts"
  version = "0.1.0"
  description = "Add your description here"
  readme = "README.md"
  requires-python = ">=3.12"
  dependencies = [
    "exifread",
    "typer",
    "rich",
    "scipy>=1.16.3",
    "pandas>=2.3.3",
]

[dependency-groups]
  dev = ["ipython"]
